### ISSUE TITLE
Should not cache 3xx responses

### ISSUE THREAD

**Issue by danlsgiga** [sillygod/cdp-cache#33]
As I'm evaluating this module, I noticed that it is not handling origin responses like 302 (Redirect). `cdp-cache` is responding with a 200 to the browser, therefore the redirect never happens!

A way to reproduce is just to proxy to an origin that does a 302 or 301.

Additionaly, it would be nice to control what responses we want to cache, usually only 200's

**Comment by sillygod** [comment]
Hi @danlsgiga,

Thanks for finding this issue and sorry for responding late. 
Recently, I am busy with other projects so I need some time to check this your PR.

**Comment by sillygod** [comment]
I'll close this issue because this bug has been fixed by another pull request #36 .
