### ISSUE TITLE
Incorrect handling of status codes.

### ISSUE THREAD

**Issue by AlbinLindskog** [sillygod/cdp-cache#35]
cdp-cache does not handle non-200 responses correctly. The content of the response is handled correctly, but the status code is changed to 200. 

Here is a bare-bones project that demonstrates the issue: https://github.com/AlbinLindskog/cpd-cache-bug

**Comment by AlbinLindskog** [comment]
Impressive! Speedy work. I've confirmed that it works in our setup. 

Consider releasing a new version with this fix. xcaddy uses the latest version, not the latest commit, so anyone installing the with xcaddy will end up with 0.4.2, unless the explicitly specify the commit.

**Comment by sillygod** [comment]
> Impressive! Speedy work. I've confirmed that it works in our setup.
> 
> Consider releasing a new version with this fix. xcaddy uses the latest version, not the latest commit, so anyone installing the with xcaddy will end up with 0.4.2, unless the explicitly specify the commit.

Sure, I will create a new release. thx.

**Comment by sillygod** [comment]
@AlbinLindskog ,

I've created a new [release](https://github.com/sillygod/cdp-cache/releases/tag/v0.4.3).

**Comment by sillygod** [comment]
@AlbinLindskog ,

If it's no more problem, I will close this ticket.
