### ISSUE TITLE
support redis & yedis

### ISSUE THREAD

**Issue by zuohuadong** [sillygod/cdp-cache#4]
consider to use redis .

like : https://docs.yugabyte.com/latest/yedis/quick-start/

**Comment by sillygod** [comment]
Thanks for filling this issue.

Currently, I am working on the purge cache function and some minor refactoring.  This plugin now supports **file cache** and **in-memory**(powered by groupcache -- it run without any external application server). It's a little lower priority to add others backend. 

To provide a bit of context.  There is an [backend interface](https://github.com/sillygod/cdp-cache/tree/master/backends) which can implement the cache backend and the Redis is actually one of your wishlists. Although, the content of the file is empty now.

I need some time to implement this :)

**Comment by sillygod** [comment]
@zuohuadong  I've added a new redis backend and test it with the redis server. That would be a big help if you can help me test with the **yedis**.
